# SPDX-FileCopyrightText: 2023 Technology Innovation Institute (TII)
#
# SPDX-License-Identifier: Apache-2.0

name: Nix meta dictionary update

on:
  push:
    branches:
      - main
  schedule:
    - cron: "5 2 * * *"

jobs:
  scheduled:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v4
    - uses: cachix/install-nix-action@v30
      with:
        nix_path: nixpkgs=channel:nixpkgs-unstable
    - name: Update nix meta dictionary
      run: ./nixmeta.sh
    - uses: stefanzweifel/git-auto-commit-action@v5
      with:
        commit_message: Automatic nix meta dictionary update
